title: Data Chefs
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
#  - name: Strategy
#    link: 'strategy/'
  - name: BabylonJS
    link: 'babylonjs/'
  - name: Learning Deep Learning
    link: 'learning-deep-learning/'
  # - name: Links
    # link: 'links'
  - name: Makers All
    link: 'https://makersall.org/'

