title: Data Chefs
author: Anders Schneiderman
email: your-email@domain.com
description:  Description of this site

# Menu data for sitewide navigation
navigation_links:
  - name: About
    link: 'about/'
  - name: 'The Road so Far'
    link: 'road/'
  # - name: Principles
  #   link: 'principles/'
  # - name: Strategy
  #   link: 'strategy/'
  # - name: Blog
  #   link: 'blog/'
  # # - name: Links
    # link: 'links'
  - name: Makers All
    link: 'https://makersall.org/'

